api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter, SimpleRouter

from series.views import SerieViewSet, ChapterViewSet

# Use DefaultRouter to see API root view (urls)
router = SimpleRouter()
router.register(r'series', SerieViewSet, basename="series")
router.register(r'chapters', ChapterViewSet, basename="chapters")

# urlpatterns = router.urls
urlpatterns = [
    path('', include(router.urls)),
]

frontend/urls.py
from django.urls import path, include
from frontend import views

urlpatterns = [
    path('', views.home, name="home"),
]

seriescraper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('frontend.urls'))
]

api/models.py
from django.db import models

# Create your models here.

frontend/models.py
from django.db import models

# Create your models here.

series/models.py
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.db import models, IntegrityError
from django.db.models import Max

from seriescraper.utils import BaseModel


# Create your models here.
class Serie(BaseModel):
    name = models.CharField(max_length=100, default=None)
    episode_list_url = models.URLField(max_length=255, default=None)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        try:
            validate = URLValidator()
            validate(self.episode_list_url)
        except ValidationError as error:
            raise IntegrityError(error.message)
        super().save(*args, **kwargs)


class ChapterManager(models.Manager):
    def last_chapters_by_series(self):
        series_with_last_chapter = Serie.objects.annotate(recent_chapter=Max('chapter__updated_at'))
        chapter_ids = series_with_last_chapter.values_list('recent_chapter', flat=True)
        return self.filter(updated_at__in=chapter_ids)

    def is_seen(self):
        return self.filter(is_seen=True)

    def not_seen(self):
        return self.filter(is_seen=False)


class Chapter(BaseModel):
    title = models.CharField(max_length=100)
    link = models.URLField(max_length=255)
    release_date = models.CharField(max_length=50)
    is_seen = models.BooleanField(default=False)
    serie_id = models.ForeignKey(Serie, on_delete=models.CASCADE)

    objects = ChapterManager()

api/views.py
from django.shortcuts import render

# Create your views here.

frontend/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'client/index.html')

series/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from series.models import Serie, Chapter
from series.serializers import SerieSerializer, ChapterSerializer
from series.tasks import process_series_data


# Create your views here.

class SerieViewSet(viewsets.ModelViewSet):
    """
    Viewset (ModelViewSet) for Serie model.
    This viewset provides automatically CRUD methods.
    """
    queryset = Serie.objects.all()
    serializer_class = SerieSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        process_series_data(request.data.get('episode_list_url'))
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


class ChapterViewSet(viewsets.ViewSet):
    """Viewset for Chapter model."""
    queryset = Chapter.objects.all()

    def list(self, request, queryset=queryset):
        serializer = ChapterSerializer(queryset, many=True)
        return Response(serializer.data)

    def create(self, request):
        serializer = ChapterSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def retrieve(self, request, pk):
        chapter = get_object_or_404(self.queryset, pk=pk)
        serializer = ChapterSerializer(chapter)
        return Response(serializer.data)

    def update(self, request, pk):
        chapter = get_object_or_404(self.queryset, pk=pk)
        serializer = ChapterSerializer(chapter, data=request.data)
        if serializer.is_valid():
            serializer.update(chapter, serializer.validated_data)
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def destroy(self, request, pk):
        chapter = get_object_or_404(self.queryset, pk=pk)
        chapter.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    @action(detail=False)
    def recent(self, request, *args, **kwargs):
        queryset = Chapter.objects.last_chapters_by_series()
        return self.list(request, queryset)

    @action(detail=False)
    def seen(self, request, *args, **kwargs):
        queryset = Chapter.objects.is_seen()
        return self.list(request, queryset)

    @action(detail=False)
    def notseen(self, request, *args, **kwargs):
        queryset = Chapter.objects.not_seen()
        return self.list(request, queryset)

frontend/templates/client/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Series</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-3">
        <h1 class="text-center">Series Scraper-Tracker</h1>
        <h6 class="text-center">Only supports Lectortmo and Webtoon websites.</h6>

        <div class="mt-5">
            <h6>Register a series</h6>
            <form id="series-form" class="row" method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col">
                    <input type="text" class="form-control" placeholder="Series name" name="name" id="id_name">
                </div>
                <div class="col">
                    <input type="url" class="form-control" placeholder="Episode list url" name="episode_list_url" id="id_episode_list_url">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-outline-primary mb-3">Register</button>
                </div>
            </form>
        </div>

        <div class="mt-3 mb-5 table-responsive ">
            <h3>Series</h3>
            <table class="table table-striped align-middle" id="seriesList">
                <thead id="seriesHead"></thead>
                <tbody id="seriesBody" class="table-border-bottom-0"></tbody>
            </table>
        </div>

        <div class="my-5">
            <h3>Recent chapters</h3>
            <table class="table table-light table-hover align-middle" id="recentChapterList">
                <thead id="recentChapterHead"></thead>
                <tbody id="recentChapterBody" class=""></tbody>
            </table>
        </div>

        <div class="my-5">
            <h3>Unseen chapters</h3>
            <table class="table table-warning table-hover align-middle" id="UnSeenChapterList">
                <thead id="UnSeenChapterHead"></thead>
                <tbody id="UnSeenChapterBody" class=""></tbody>
            </table>
        </div>

        <div class="my-5">
            <h3>Seen chapters</h3>
            <table class="table table-info table-hover align-middle" id="seenChapterList">
                <thead id="seenChapterHead"></thead>
                <tbody id="seenChapterBody" class=""></tbody>
            </table>
        </div>

        <!--Chapters Modal -->
        <div class="modal fade" id="chapter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true" data-bs-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel"></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p class="text-center"></p>
                        <form id="chapter-action-form" class="button-form" data-method="" method="POST" action="">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="series-id-name" class="col-form-label col-form-label-sm">Series name</label>
                                <input type="text" id="series-id-name" name="serie_id" class="form-control form-control-sm" readonly>
                            </div>
                            <div class="mb-3">
                                <label for="chapter-title" class="col-form-label-sm">Title</label>
                                <input type="text" class="form-control form-control-sm" id="chapter-title" name="title" readonly>
                            </div>
                            <div class="mb-3">
                                <label for="chapter-link" class="col-form-label-sm">Link</label>
                                <input type="url" class="form-control form-control-sm" id="chapter-link" name="link" readonly>
                            </div>
                            <div class="mb-3">
                                <label for="chapter-release-date" class="col-form-label-sm">Release date</label>
                                <input type="text" class="form-control form-control-sm" id="chapter-release-date" name="release_date" readonly>
                            </div>
                            <div class="mb-3 form-check">
                                <input class="form-check-input form-check-input-sm" type="hidden" id="chapter-is-seen" name="is_seen" value="false">
                                <label class="form-check-label-sm" for="chapter-is-seen">Was seen?</label>
                                <input class="form-check-input form-check-input-sm" type="checkbox" id="chapter-is-seen" name="is_seen">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" id="chapter-action-btn" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!--Series Modal -->
        <div class="modal fade" id="series-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true" data-bs-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel"></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p class="text-center"></p>
                        <form id="series-action-form" class="button-form" data-method="" method="POST" action="">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="series-name" class="col-form-label">Name</label>
                                <input type="text" class="form-control" id="series-name" name="name">
                            </div>
                            <div class="mb-3">
                                <label for="series-url" class="col-form-label">Episode list url</label>
                                <textarea type="text" class="form-control" id="series-url" name="episode_list_url"></textarea>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" id="action-btn" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src={% static "assets/js/utils.js" %}></script>
</body>
</html>